### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by garudaonekh** [chadfawcett/smart-phone-chlorine-sampler#3]
Hi, very interested with your project

Is it accurate?

Thanks

**Comment by chadfawcett** [comment]
Hey there. This was a school project many years ago. I don't recall the exact accuracy capabilities. From what I remember, it wasn't super accurate. 

You can see the final report here https://github.com/chadfawcett/chlorine-sampler/blob/master/report/REPORT.md
